# Generated by Django 5.1.7 on 2025-03-26 17:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EliteProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("model", models.CharField(max_length=50, verbose_name="Модель")),
                ("release_date", models.DateField(verbose_name="Дата выхода")),
            ],
            options={
                "verbose_name": "Продукт EliteGrid",
                "verbose_name_plural": "Продукты EliteGrid",
            },
        ),
        migrations.CreateModel(
            name="GridNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название узла"),
                ),
                (
                    "node_type",
                    models.IntegerField(
                        choices=[(0, "Завод"), (1, "Розничная сеть"), (2, "ИП")],
                        verbose_name="Тип узла",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Задолженность",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудники",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        to="nodelink.eliteproduct", verbose_name="Продукты"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nodelink.gridnode",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Узел EliteGrid",
                "verbose_name_plural": "Узлы EliteGrid",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NodeContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("street", models.CharField(max_length=100, verbose_name="Улица")),
                ("building", models.CharField(max_length=10, verbose_name="Дом")),
                (
                    "grid_node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_info",
                        to="nodelink.gridnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт узла",
                "verbose_name_plural": "Контакты узлов",
            },
        ),
        migrations.AddField(
            model_name="gridnode",
            name="contact",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="nodelink.nodecontact",
                verbose_name="Контакты",
            ),
        ),
    ]
