# Generated by Django 5.1.7 on 2025-03-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodelink", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nodecontact",
            options={
                "verbose_name": "Контакт звена",
                "verbose_name_plural": "Контакты звеньев",
            },
        ),
        migrations.AlterField(
            model_name="gridnode",
            name="node_type",
            field=models.IntegerField(
                choices=[(0, "Завод"), (1, "Розничная сеть"), (2, "ИП")],
                verbose_name="Тип звена",
            ),
        ),
        migrations.AlterField(
            model_name="gridnode",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название звена"),
        ),
    ]
