# Generated by Django 5.1.7 on 2025-03-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "nodelink",
            "0002_alter_nodecontact_options_alter_gridnode_node_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gridnode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Звено EliteGrid",
                "verbose_name_plural": "Звенья EliteGrid",
            },
        ),
    ]
